authors = ["Sergey Nechoroshev <sergo777ser777@gmail.com>"]
description = "A curated collection of blurred, hybrid, and flat themes for Zed, bringing beloved Neovim palettes and carefully tuning Zed’s themes for modern UI surfaces with clean contrast and consistent syntax colors."
id = "blurred-hybrid-collection"
name = "Blurred Hybrid Collection"
repository = "https://github.com/SergoGansta777/BlurredZedThemes"
schema_version = 1
version = "0.1.0"
